name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    check-macos:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
      runs-on:  ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3
        - name: Build C check
          run:  gcc pathconf_test.c  -o pathconf_test_c
        - name: List files
          run:  ls
        - name: Run C check
          run:  ./pathconf_test_c
        - name: Run Rust check
          run: cargo run
        - name: Run Python check
          run: python3 pathconf-test.py
